apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-2
  namespace: default
  labels:
    app: application
spec:
  selector:
    matchLabels:
      app: application
  replicas: 2
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: azima/nodejs-test:latest
          resources: {}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 2
          #   successThreshold: 1
          #   failureThreshold: 3
            # periodSeconds: 10
          # env:
          #   - name: DB_HOST
          #     valueFrom:
          #       configMapKeyRef:
          #         name: DATABASE_CONFIG
          #         key: DB_HOST
          #   - name: DB_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: DATABASE_CONFIG
          #         key: DB_PASSWORD
          ports:
            - containerPort: 3000
              protocol: TCP
              name: application
          volumeMounts:
            - name: localtime
              mountPath: /app/nodejs
      volumes:
        - name: localtime
          hostPath:
            path: /app
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs
  namespace: default
spec:
  selector:
    app: application
  type: NodePort

  ports:
  - name: nodejs
    protocol: TCP
    port: 3000
    targetPort: 3000
